<template>
  <main class="auth-page"><section class="brand-panel"><div class="brand-lockup"><div class="brand-mark"><el-icon><Box /></el-icon></div><div><strong>智能仓储</strong><span>WAREHOUSE CONSOLE</span></div></div><div class="brand-copy"><p class="eyebrow">OPERATIONS PLATFORM</p><h1>仓储管理控制台</h1><p>统一管理库存、温湿度、设备状态与操作记录。</p></div><div class="platform-status"><span><i></i>系统服务</span><b>在线</b></div></section><section class="auth-panel"><div class="form-shell"><div class="form-context"><p>{{ isRegister ? 'CREATE ACCOUNT' : 'SIGN IN' }}</p><h2>{{ isRegister ? '注册账号' : '欢迎登录' }}</h2><span>{{ isRegister ? '填写信息以创建仓储系统账号。' : '使用您的账号进入仓储工作台。' }}</span></div><div class="form-stage"><login-form :class="{ hidden: isRegister }" @switch-to-register="isRegister = true" /><register-form :class="{ visible: isRegister }" @switch-to-login="isRegister = false" /></div></div><p class="auth-footer">智能仓储管理系统</p></section></main>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Box } from '@element-plus/icons-vue'
import LoginForm from '@/components/login/loginForm.vue'
import RegisterForm from '@/components/login/registerForm.vue'
const isRegister = ref(false)
</script>

<style scoped>
.auth-page { display: grid; grid-template-columns: minmax(360px, .9fr) minmax(460px, 1.1fr); width: 100vw; min-height: 100vh; overflow: hidden; background: #252a2f; color: #edf3f8; }.brand-panel { display: flex; flex-direction: column; min-height: 100vh; padding: 36px clamp(32px, 6vw, 92px); border-right: 1px solid #414b55; background: #292f35; }.brand-lockup { display: flex; align-items: center; gap: 11px; }.brand-mark { display: grid; width: 38px; height: 38px; place-items: center; border: 1px solid #527493; border-radius: 6px; background: #213a50; color: #83c3ef; font-size: 20px; }.brand-lockup strong, .brand-lockup span { display: block; }.brand-lockup strong { font-size: 18px; }.brand-lockup span { margin-top: 3px; color: #82919f; font-size: 10px; }.brand-copy { margin: auto 0; }.eyebrow { margin: 0 0 10px; color: #83c3ef; font-size: 12px; font-weight: 600; }.brand-copy h1 { margin: 0; font-size: 34px; font-weight: 600; }.brand-copy > p:last-child { max-width: 390px; margin: 14px 0 0; color: #aebbc6; font-size: 15px; line-height: 1.75; }.platform-status { display: flex; align-items: center; justify-content: space-between; padding-top: 18px; border-top: 1px solid #414b55; color: #aebbc6; font-size: 13px; }.platform-status span { display: inline-flex; align-items: center; gap: 7px; }.platform-status i { width: 7px; height: 7px; border-radius: 50%; background: #72c781; }.platform-status b { color: #72c781; font-weight: 500; }.auth-panel { display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh; padding: 32px; background: #252a2f; }.form-shell { width: min(400px, 100%); }.form-context { margin-bottom: 28px; }.form-context p { margin: 0 0 7px; color: #83c3ef; font-size: 12px; font-weight: 600; }.form-context h2 { margin: 0; font-size: 26px; font-weight: 600; }.form-context span { display: block; margin-top: 9px; color: #aebbc6; font-size: 14px; }.form-stage { position: relative; min-height: 305px; }.auth-footer { margin: 30px 0 0; color: #748391; font-size: 12px; }@media (max-width: 800px) { .auth-page { grid-template-columns: 1fr; }.brand-panel { min-height: auto; padding: 24px; border-right: 0; border-bottom: 1px solid #414b55; }.brand-copy, .platform-status { display: none; }.auth-panel { min-height: calc(100vh - 87px); }.form-shell { width: min(420px, 100%); } }@media (max-width: 460px) { .auth-panel { padding: 24px 18px; }.form-context h2 { font-size: 24px; } }
</style>
