-- Creates the telemetry tables expected by the API when a source database
-- has not been imported yet. Existing tables are left unchanged.
CREATE TABLE IF NOT EXISTS `101` (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  wendu DECIMAL(6,2) NOT NULL,
  shidu DECIMAL(6,2) NOT NULL,
  time DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_101_time (time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `102` LIKE `101`;
CREATE TABLE IF NOT EXISTS `108` LIKE `101`;
CREATE TABLE IF NOT EXISTS `109` LIKE `101`;
CREATE TABLE IF NOT EXISTS `113` LIKE `101`;
CREATE TABLE IF NOT EXISTS `115` LIKE `101`;
CREATE TABLE IF NOT EXISTS `116` LIKE `101`;
CREATE TABLE IF NOT EXISTS `117` LIKE `101`;
CREATE TABLE IF NOT EXISTS `118` LIKE `101`;
CREATE TABLE IF NOT EXISTS `119` LIKE `101`;
